name: Build IPA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-26
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Xcode
      run: sudo xcode-select -s /Applications/Xcode.app
    
    - name: Build
      run: |
        cd PoC
        xcodebuild -project UAFTester.xcodeproj \
                   -scheme UAFTester \
                   -configuration Release \
                   -archivePath UAFTester.xcarchive \
                   archive
        
        xcodebuild -exportArchive \
                   -archivePath UAFTester.xcarchive \
                   -exportPath output \
                   -exportOptionsPlist exportOptions.plist
    
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: UAFTester-IPA
        path: PoC/output/*.ipa
