name: Build PoC for iOS
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-26 # Dùng macOS mới nhất của Github
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Highest Xcode Version
              run: |
                # Liệt kê các bản Xcode có sẵn để cậu dễ debug nếu lỗi lại xảy ra
                ls /Applications/ | grep Xcode
                # Tự động chọn bản Xcode mới nhất có trên máy
                latest_xcode=$(ls /Applications/ | grep Xcode_ | sort -V | tail -n 1)
                sudo xcode-select -s "/Applications/$latest_xcode/Contents/Developer"
                xcodebuild -version

      - name: Build App
        run: |
          cd PoC
          xcodebuild -project UAFTester.xcodeproj \
                     -scheme UAFTester \
                     -configuration Release \
                     -sdk iphoneos \
                     -derivedDataPath build \
                     CODE_SIGNING_ALLOWED=NO \
                     CODE_SIGN_ING_REQUIRED=NO

      - name: Create IPA (Fake Sign)
        run: |
          mkdir -p Payload
          cp -r PoC/build/Build/Products/Release-iphoneos/UAFTester.app Payload/
          zip -r UAFTester.ipa Payload

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: UAFTester-IPA
          path: UAFTester.ipa
